### ISSUE TITLE
Keyboard covers focused input element on iOS 11

### ISSUE THREAD

**Issue by jeffminsungkim** [jeffminsungkim/Ashy#17]
### Version info
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v8.9.0
    npm        : 5.5.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

### Issue content
When I click the text input from the modal, a keyboard overlaps the text input. This issue has found during testing on iPhone SE (iOS 11) device.

### Expected behavior
Ion input should stay in a position right above the keyboard while a user types some messages.

### Actual behavior
![](https://media.giphy.com/media/l4EoRxzoKufITvC2Q/giphy.gif)

**Comment by jeffminsungkim** [comment]
The Ionic team still having this issue.
This [thread](https://github.com/ionic-team/ionic/issues/7149) describes the same problem as mine.

**Comment by jeffminsungkim** [comment]
![ios-keyboard-bug-fixed](https://user-images.githubusercontent.com/6092023/34343546-27717714-ea17-11e7-8f3a-bae0a5c92f17.gif)

**Comment by wenjianli92** [comment]
hi，How do you solve it, please let me know, thank you
